import maliang as ml

def resource_path(relative_path: str) -> str: ...

def get_exit_ask(root_window: ml.Tk): ...

def get_pick(root_window: ml.Tk, sub_cav_1: ml.Canvas, sub_cav_2: ml.Canvas): ...

def get_pick_people(root_window: ml.Tk, sub_cav: ml.Canvas, text: ml.Text): ...

def get_pick_card(root_window: ml.Tk, sub_cav: ml.Canvas, text: ml.Text time: int): ...
